const constants = {
  ADD_TEAM: "ADD_TEAM",
  REMOVE_TEAM: "REMOVE_TEAM",
  FETCH_TEAM: "FETCH_TEAM",
  ADD_PLAYER: "ADD_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  FETCH_PLAYER: "FETCH_PLAYER",
  FETCH_PLAYERS: "FETCH_PLAYERS",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  CHANGE_PLAYER_SUGGESTIONS: "CHANGE_PLAYER_SUGGESTIONS",
  CLEAR_PLAYER_SUGGESTIONS: "CLEAR_PLAYER_SUGGESTIONS"
};


export default constants;
